name: Build and Deploy

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      deploy_command:
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c처digo
        uses: actions/checkout@v4

      - name: Listar arquivos no diret처rio
        run: ls -la

      - name: Setup Go
        if: ${{ inputs.language == 'go' }}
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Java
        if: ${{ inputs.language == 'java' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build projeto
        run: |
          echo "Rodando build para linguagem: ${{ inputs.language }}"
          if [[ "${{ inputs.language }}" == "go" ]]; then
            go build -o app main.go || echo "Sem arquivo Go"
          elif [[ "${{ inputs.language }}" == "java" ]]; then
            ./gradlew build || mvn clean package || echo "Sem build Java"
          else
            echo "Linguagem n찾o suportada"
            exit 1
          fi

      - name: Rodar testes
        run: |
          echo "Rodando testes para linguagem: ${{ inputs.language }}"
          if [[ "${{ inputs.language }}" == "go" ]]; then
            go test ./...
          elif [[ "${{ inputs.language }}" == "java" ]]; then
            ./gradlew test || mvn test
          else
            echo "Linguagem n찾o suportada"
            exit 1
          fi

      - name: Deploy (opcional)
        if: ${{ inputs.deploy_command }}
        run: ${{ inputs.deploy_command }}
